### ISSUE TITLE
build and run ./zello but not work

### ISSUE THREAD

**Issue by cevo2022** [cpesoft/zello-bot#4]
I did following steps but it didnt work 

1. build the docker but it got stucked at cleaning step however it seems to have no impact to the docker, so I disabled it.
2.  I start the docker terminal and cd /root/zello and  config all username and password in Zello.config
3. execute ./zello 
result is return nothing, how I can test the result ? Do you have detail tutorial ?

**Comment by cpesoft** [comment]
This once was a proof-of-concept only.
The idea was to build a docker container to run zello.exe via WINE (winehq.com)
The container runs a vnc server (password can be set in docker-compose.yml) with minimal gui, so you can start (and configure) zello from there.

But since Zello provides a custom API nowadays (https://github.com/zelloptt/zello-channel-api) consider this project as stale and outdated. Sorry.
